driver:
  name: docker

platforms:
  - name: centos-7
    driver_config:
      image: corux/centos7-salt

provisioner:
  name: salt_solo
  formula: selinux
  pillars-from-files:
    selinux.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - selinux
  state_top:
    base:
      "*":
        - selinux

suites:
  - name: default
